### ISSUE TITLE
Errors on go get (too few values in discordgo.MessageReaction literal)

### ISSUE THREAD

**Issue by w3bb** [tsudoko/pullcord#19] opened 2019-09-26 19:11 UTC
``
../../go/src/github.com/tsudoko/pullcord/logpull/main.go:372:62: too few values in discordgo.MessageReaction literal``

``
../../go/src/github.com/tsudoko/pullcord/logpull/main.go:381:60: too few values in discordgo.MessageReaction literal``

**Comment by tsudoko** [comment] 2020-01-06 05:28
Should be fixed in 64699af8bb3114bef0f6d4ecb1f60609b4ea691a, but I have no idea how this happened in the first place, since the vendored version of `discordgo` was compatible with `MessageReaction` literals as used in the code at the time. Couldn't reproduce the error either, I suspect `go get` wasn't picking up the vendored package for some reason.

**Closed by tsudoko** 2020-01-06 05:28 UTC
